# Generated by Django 4.1.1 on 2022-09-22 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dispatch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('tractor', models.CharField(max_length=20)),
                ('pickup_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('action', models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Scheduled', max_length=10)),
                ('commodity', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=20)),
                ('pickup_arrival_date', models.DateTimeField(null=True)),
                ('pickup_departure_date', models.DateTimeField(null=True)),
                ('pickup_arrival', models.BooleanField(default=False)),
                ('departure_from_pickup', models.BooleanField(default=False)),
                ('delivery_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('delivery_arrival_date', models.DateTimeField(null=True)),
                ('delivery_departure_date', models.DateTimeField(null=True)),
                ('delivery_arrival', models.BooleanField(default=False)),
                ('delivery_departure', models.BooleanField(default=False)),
                ('pod', models.TextField(blank=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=30)),
                ('person', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('weight', models.CharField(default='', max_length=20)),
                ('packages', models.CharField(default='', max_length=20)),
                ('shipper', models.CharField(default='', max_length=100)),
                ('pickup', models.DateTimeField(null=True)),
                ('delivery', models.DateTimeField(null=True)),
                ('dispatch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='trucking_app.dispatch')),
            ],
        ),
    ]
