# Generated by Django 4.1.1 on 2022-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0002_alter_dispatch_pod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='pod',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
