# Generated by Django 4.1.1 on 2022-09-22 13:59

from django.db import migrations, models
import trucking_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0004_alter_dispatch_pod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='pod',
            field=models.FileField(blank=True, upload_to=trucking_app.models.upload_to),
        ),
    ]
