# Generated by Django 4.1.1 on 2022-10-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0005_alter_dispatch_pod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='action',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='delivery_arrival',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='delivery_arrival_date',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='delivery_departure',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='delivery_departure_date',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='departure_from_pickup',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='pickup_arrival',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='pickup_arrival_date',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='pickup_departure_date',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='pod',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='tractor',
        ),
    ]
