# Generated by Django 4.1.1 on 2022-10-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0006_remove_dispatch_action_remove_dispatch_commodity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='owner',
        ),
    ]
