# Generated by Django 4.1.1 on 2022-10-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0008_dispatch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='order',
            name='person',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
    ]
