# Generated by Django 4.1.1 on 2022-10-11 08:14

from django.db import migrations, models
import location_field.models.plain
import trucking_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('trucking_app', '0009_remove_order_delivery_remove_order_packages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='action',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Scheduled', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='commodity',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_arrival',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_arrival_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_departure',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_departure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='departure_from_pickup',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pickup_arrival',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pickup_arrival_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pickup_departure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pickup_location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='pod',
            field=models.FileField(null=True, upload_to=trucking_app.models.upload_to),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='tractor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packages',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
