name: Dispatches CI

on:
  pull_request:

jobs:
  build-test:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_NAME: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        python3 manage.py migrate
    - name: Run tox
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        tox
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        pytest