name: Dispatches CI

on:
  pull_request:

jobs:
  build-test:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:10.8
        # Provide the password for postgres
        env:
          POSTGRES_NAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
      run: python3 manage.py migrate
    - name: Run tox
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        tox
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        pytest